remote_theme: rundocs/jekyll-rtd-theme
title: Research Computing Services Franklin and Marshall College

nav_version: true
edit: false

readme_index:
  with_frontmatter: true

  sass:
  style: compressed